import RPi.GPIO as GPIO
import time
while True:
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(17,GPIO.OUT)
    GPIO.setup(18,GPIO.OUT)
    GPIO.setup(22,GPIO.OUT)
    GPIO.setup(23,GPIO.OUT)
    GPIO.output(17,True)
    time.sleep(0.5)
    GPIO.output(17,False)
    time.sleep(0.5)
    GPIO.output(17,True)
    time.sleep(0.5)
    GPIO.output(17,False)
    time.sleep(0.5)
    GPIO.output(22,True)
    time.sleep(0.5)
    GPIO.output(22,False)
    time.sleep(0.5)
    GPIO.output(23,True)
    time.sleep(0.5)
    GPIO.output(23,False)