import cv2
image=cv2.imread("../EP-12.3.25/img_1.png")
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
_, binary=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
adaptive=cv2.adaptiveThreshold(gray,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,11,2)
_, otsu_thresh=cv2.threshold(gray,127,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
edges=cv2.Canny(gray, 100,200)
cv2.imshow("Original image",image)
cv2.imshow("Gray image",gray)
cv2.imshow("Binary Thresholding image",binary)
cv2.imshow("Adaptive Thresholding image",adaptive)
cv2.imshow("Otsu algo image",otsu_thresh)
cv2.imshow("Canny edge detection",edges)
cv2.waitKey(0)
cv2.destroyAllWindows()